ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 24.12.2014 0:2:55
user Marek
END
objects 20       
END

[% zCMaterial 17408 0]
	name=string:CA_MISC2
	matGroup=enum:1
	color=color:26 27 25 255
	smoothAngle=float:60
	texture=string:CA_MISC2.TGA
	texScale=string:2048 2048
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:CA_TORCH_01
	matGroup=enum:3
	color=color:61 57 50 255
	smoothAngle=float:90
	texture=string:CA_TORCH_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:CA_MUNITION
	matGroup=enum:3
	color=color:49 43 36 255
	smoothAngle=float:60
	texture=string:CA_MUNITION.TGA
	texScale=string:512 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:CA_BOWS
	matGroup=enum:3
	color=color:68 57 46 255
	smoothAngle=float:60
	texture=string:CA_BOWS.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:CA_BOWS2
	matGroup=enum:3
	color=color:37 28 21 255
	smoothAngle=float:60
	texture=string:CA_BOWS2.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:CA_BOW_HANDLES
	matGroup=enum:3
	color=color:41 33 27 255
	smoothAngle=float:60
	texture=string:CA_BOW_HANDLES.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:CA_FOOD
	matGroup=enum:0
	color=color:90 65 40 255
	smoothAngle=float:60
	texture=string:CA_FOOD.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:CA_PLANTS
	matGroup=enum:0
	color=color:45 42 33 255
	smoothAngle=float:60
	texture=string:CA_PLANTS.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:CA_BOTTLES
	matGroup=enum:1
	color=color:54 56 48 255
	smoothAngle=float:60
	texture=string:CA_BOTTLES.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:CA_KEYS
	matGroup=enum:1
	color=color:32 27 20 255
	smoothAngle=float:60
	texture=string:CA_KEYS.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:CA_POTIONS
	matGroup=enum:2
	color=color:56 54 55 255
	smoothAngle=float:60
	texture=string:CA_POTIONS.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:CA_MISC
	matGroup=enum:1
	color=color:58 55 48 255
	smoothAngle=float:60
	texture=string:CA_MISC.TGA
	texScale=string:2048 2048
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:CA_ALPHA
	matGroup=enum:0
	color=color:255 255 255 255
	smoothAngle=float:60
	texture=string:CA_ALPHA.TGA
	texScale=string:8 8
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:CA_TORCH_02
	matGroup=enum:3
	color=color:53 44 38 255
	smoothAngle=float:60
	texture=string:CA_TORCH_02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:CA_CHAIR
	matGroup=enum:3
	color=color:29 26 20 255
	smoothAngle=float:60
	texture=string:CA_CHAIR.TGA
	texScale=string:2048 2048
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:CA_CBOW1
	matGroup=enum:1
	color=color:39 35 30 255
	smoothAngle=float:60
	texture=string:CA_CBOW1.TGA
	texScale=string:2048 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:CA_CBOW2
	matGroup=enum:1
	color=color:69 67 60 255
	smoothAngle=float:60
	texture=string:CA_CBOW2.TGA
	texScale=string:2048 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:CA_CBOW3
	matGroup=enum:1
	color=color:30 31 29 255
	smoothAngle=float:60
	texture=string:CA_CBOW3.TGA
	texScale=string:2048 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:CA_CBOW
	matGroup=enum:1
	color=color:55 46 38 255
	smoothAngle=float:60
	texture=string:CA_CBOW.TGA
	texScale=string:2048 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:CA_BENCH
	matGroup=enum:3
	color=color:48 44 33 255
	smoothAngle=float:60
	texture=string:CA_BENCH.TGA
	texScale=string:2048 2048
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
